:sources:
  SampleAdapter:
    poll_interval: 300
    priority: 1
  SimpleAdapter:
    poll_interval: 600
    partition_type: 'app'
  FixedSchemaAdapter:
    poll_interval: 300
    priority: 5
    sync_type: 'incremental'
    belongs_to: 
      - brand: 'SampleAdapter'
    
:development:
  :licensefile: settings/license.key
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :licensefile: settings/license.key
  :iphonecertfile: settings/apple_fake_cert.pem
  :iphonepassphrase: certpassword
  :iphoneserver: gateway.sandbox.push.apple.com
  :iphoneport: 2195  
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :bulk_sync_poll_interval: 3600
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/